### ISSUE TITLE
The remote name could not be resolved: 'system.management.automation.pscredential'

### ISSUE THREAD

**Issue by the-joey-o** [umn-microsoft-automation/UMN-Qualys#23]
Hi, I'm running into the following error when I try to filter on Get-QualysHostAsset:

> The remote name could not be resolved: 'system.management.automation.pscredential'

Here's the code I'm running (running in an Azure Automation Runbook):

`$qualysCred = Get-AutomationPSCredential -Name 'QualysAPIAccount'`
`$qualysServer = "qualysapi.qg2.apps.qualys.com"`
`$cookie = Connect-Qualys -qualysCred $qualysCred -qualysServer $qualysServer`
`Get-QualysHostAsset -filter @{use_tags=1;tag_set_include=12650426} -qualysServer $qualysCred -cookie $cookie`

Not sure if I'm doing something wrong or if the module has a bug. Any help you could provide would be much appreciated!

**Comment by travis-sobeck** [comment]
> -qualysServer $qualysCred 
You're trying to put in the $qualysCred as the server ....
What you want is:
-qualysServer $qualysServer

**Comment by the-joey-o** [comment]
Bah! How did I miss that? Thank you!

**Comment by travis-sobeck** [comment]
No problem
